<a href="https://colab.research.google.com/github/wjdrnqja9/TIL/blob/main/deep_learning/04_05_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Tensor Operations

In [1]:
import torch

## Arithmetic Element-wise Operations

In [12]:
a = torch.FloatTensor([[1, 2],
                       [3, 4]])
b = torch.FloatTensor([[2, 2],
                       [3, 3]])

In [3]:
a + b

tensor([[3., 4.],
        [6., 7.]])

In [4]:
a - b

tensor([[-1.,  0.],
        [ 0.,  1.]])

In [5]:
a * b

tensor([[ 2.,  4.],
        [ 9., 12.]])

In [6]:
a / b

tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])

In [7]:
a == b

tensor([[False,  True],
        [ True, False]])

In [8]:
a != b

tensor([[ True, False],
        [False,  True]])

In [9]:
a ** b

tensor([[ 1.,  4.],
        [27., 64.]])

## Inplace Operations

In [13]:
print(a)
print(a.mul(b)) # a * b
print(a)
print(a.mul_(b)) # 덮어씌움
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])


## Sum, Mean (Dimension Reducing Operations)

In [14]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])

In [15]:
print(x.sum())
print(x.mean())

tensor(10.)
tensor(2.5000)


In [16]:
print(x.sum(dim=0))
print(x.sum(dim=-1))

tensor([4., 6.])
tensor([3., 7.])


## Broadcast in Operations

What we did before,

In [17]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[4, 8]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([1, 2])


In [18]:
z = x + y
print(z)
print(z.size())

tensor([[ 5., 10.]])
torch.Size([1, 2])


Broadcast feature provides operations between different shape of tensors.

### Tensor + Scalar

In [19]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
y = 1

print(x.size())

torch.Size([2, 2])


In [20]:
z = x + y
print(z)
print(z.size())

tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


### Tensor + Vector

In [21]:
x = torch.FloatTensor([[1, 2],
                       [4, 8]])
y = torch.FloatTensor([3,
                       5])

print(x.size())
print(y.size())

torch.Size([2, 2])
torch.Size([2])


In [22]:
z = x + y
print(z)
print(z.size())

tensor([[ 4.,  7.],
        [ 7., 13.]])
torch.Size([2, 2])


In [23]:
x = torch.FloatTensor([[[1, 2]]])
y = torch.FloatTensor([3,
                       5])

print(x.size())
print(y.size())

torch.Size([1, 1, 2])
torch.Size([2])


In [24]:
z = x + y
print(z)
print(z.size())

tensor([[[4., 7.]]])
torch.Size([1, 1, 2])


### Tensor + Tensor

In [25]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[3],
                       [5]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([2, 1])


In [26]:
z = x + y
print(z)
print(z.size())

tensor([[4., 5.],
        [6., 7.]])
torch.Size([2, 2])


Note that you need to be careful before using broadcast feature.

### Failure Case

In [27]:
x = torch.FloatTensor([[[1, 2],
                        [4, 8]]])
y = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

print(x.size())
print(y.size())

z = x + y

torch.Size([1, 2, 2])
torch.Size([3, 3])


RuntimeError: ignored