<a href="https://colab.research.google.com/github/wjdrnqja9/TIL/blob/main/deep_learning/04_08_tensor_useful_methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Useful Methods

In [1]:
import torch

### expand: copy the given tensor and concat those at desired dimension.

In [2]:
x = torch.FloatTensor([[[1, 2]],
                       [[3, 4]]])
print(x.size())

torch.Size([2, 1, 2])


In [3]:
y = x.expand(*[2, 3, 2])

print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


#### Implement expand with cat.

In [4]:
y = torch.cat([x, x, x], dim=1)

print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


### randperm: Random Permutation

In [5]:
x = torch.randperm(10)

print(x)
print(x.size())

tensor([8, 2, 7, 1, 0, 4, 3, 5, 6, 9])
torch.Size([10])


### argmax: Return index of maximum values

In [6]:
x = torch.randperm(3**3).reshape(3, 3, -1)

print(x)
print(x.size())

tensor([[[ 7, 20,  4],
         [ 8, 23, 18],
         [17, 19, 21]],

        [[13,  0,  2],
         [ 1,  9, 26],
         [16, 14, 25]],

        [[11, 10, 15],
         [ 3,  5, 12],
         [22,  6, 24]]])
torch.Size([3, 3, 3])


In [7]:
y = x.argmax(dim=-1)

print(y)
print(y.size())

tensor([[1, 1, 2],
        [0, 2, 2],
        [2, 2, 2]])
torch.Size([3, 3])


### topk: Return tuple of top-k values and indices.

In [8]:
values, indices = torch.topk(x, k=1, dim=-1)

print(values.size())
print(indices.size())

torch.Size([3, 3, 1])
torch.Size([3, 3, 1])


Note that topk didn't reduce the dimension, even in $k=1$ case.

In [9]:
print(values.squeeze(-1))
print(indices.squeeze(-1))

tensor([[20, 23, 21],
        [13, 26, 25],
        [15, 12, 24]])
tensor([[1, 1, 2],
        [0, 2, 2],
        [2, 2, 2]])


In [10]:
print(x.argmax(dim=-1) == indices.squeeze(-1))

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [11]:
_, indices = torch.topk(x, k=2, dim=-1)
print(indices.size())

print(x.argmax(dim=-1) == indices[:, :, 0])

torch.Size([3, 3, 2])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


### Sort by using topk

In [12]:
target_dim = -1
values, indices = torch.topk(x,
                             k=x.size(target_dim),
                             largest=True)

print(values)

tensor([[[20,  7,  4],
         [23, 18,  8],
         [21, 19, 17]],

        [[13,  2,  0],
         [26,  9,  1],
         [25, 16, 14]],

        [[15, 11, 10],
         [12,  5,  3],
         [24, 22,  6]]])


### Topk by using sort

In [13]:
k=1
values, indices = torch.sort(x, dim=-1, descending=True)
values, indices = values[:, :, :k], indices[:, :, :k]

print(values.squeeze(-1))
print(indices.squeeze(-1))

tensor([[20, 23, 21],
        [13, 26, 25],
        [15, 12, 24]])
tensor([[1, 1, 2],
        [0, 2, 2],
        [2, 2, 2]])


### masked_fill: fill the value if element of mask is True.

In [14]:
x = torch.FloatTensor([i for i in range(3**2)]).reshape(3, -1)

print(x)
print(x.size())

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
torch.Size([3, 3])


In [15]:
mask = x > 4

print(mask)

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])


In [16]:
y = x.masked_fill(mask, value=-1)

print(y)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])


### Ones and Zeros

In [17]:
print(torch.ones(2, 3))
print(torch.zeros(2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [18]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6]])
print(x.size())

torch.Size([2, 3])


In [19]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
