<a href="https://colab.research.google.com/github/wjdrnqja9/TIL/blob/main/deep_learning/05_05_use_gpu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How to use GPU

In [1]:
import torch
import torch.nn as nn

## Convert to CUDA tensor: cuda()

In [ ]:
x = torch.cuda.FloatTensor(2, 2)

x

In [ ]:
x = torch.FloatTensor(2, 2)

x

In [ ]:
x.cuda()

tensor([[-4.4256e-10,  4.5685e-41],
        [-4.4256e-10,  4.5685e-41]], device='cuda:0')

In [ ]:
d = torch.device('cuda:0')

In [ ]:
x.cuda(device=d)

tensor([[-4.4256e-10,  4.5685e-41],
        [-4.4256e-10,  4.5685e-41]], device='cuda:0')

In [ ]:
x.device

device(type='cpu')

## Convert to CUDA tensor: to()

In [ ]:
x.to(device=d)

tensor([[-4.4256e-10,  4.5685e-41],
        [-4.4256e-10,  4.5685e-41]], device='cuda:0')

## Convert to CPU tensor from CUDA tensor

In [ ]:
x = torch.cuda.FloatTensor(2, 2)

In [ ]:
x = x.cpu()

In [ ]:
d = torch.device('cpu')
x = x.to(d)

## Move model from CPU to GPU.

In [ ]:
def print_params(model):
    for p in model.parameters():
        print(p)

In [ ]:
linear = nn.Linear(2, 2)

print_params(linear)

Parameter containing:
tensor([[ 0.5782,  0.4288],
        [-0.0220, -0.1614]], requires_grad=True)
Parameter containing:
tensor([0.6881, 0.0907], requires_grad=True)


In [ ]:
linear = linear.cuda()

print_params(linear)

Parameter containing:
tensor([[ 0.5782,  0.4288],
        [-0.0220, -0.1614]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([0.6881, 0.0907], device='cuda:0', requires_grad=True)


In [ ]:
linear = linear.cpu()

print_params(linear)

Parameter containing:
tensor([[ 0.5782,  0.4288],
        [-0.0220, -0.1614]], requires_grad=True)
Parameter containing:
tensor([0.6881, 0.0907], requires_grad=True)


In [ ]:
d = torch.device('cuda:0')
linear = linear.to(d)

print_params(linear)

Parameter containing:
tensor([[ 0.5782,  0.4288],
        [-0.0220, -0.1614]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([0.6881, 0.0907], device='cuda:0', requires_grad=True)


Note that nn.Module class does not have 'device' property.

In [ ]:
linear.device

AttributeError: 'Linear' object has no attribute 'device'

## Tricks

In [ ]:
x = torch.cuda.FloatTensor(2, 2)

In [ ]:
x.new(2, 2)

tensor([[2.3694e-38, 1.2422e-01],
        [1.4013e-45, 0.0000e+00]], device='cuda:0')

In [ ]:
torch.zeros_like(x)

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [ ]:
torch.ones_like(x)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [ ]:
list(linear.parameters())[0].new(2, 2)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')