<a href="https://colab.research.google.com/github/wjdrnqja9/TIL/blob/main/deep_learning/07_03_auto_grad_checkpoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch AutoGrad

In [1]:
import torch

In [2]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]]).requires_grad_(True)

In [3]:
x1 = x + 2
x2 = x - 2
x3 = x1 * x2
y = x3.sum()

print(x1)
print(x2)
print(x3)
print(y)

tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)
tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)
tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>)
tensor(14., grad_fn=<SumBackward0>)


In [4]:
y.backward()

$$\begin{gathered}
x=\begin{bmatrix}
x_{(1,1)} & x_{(1,2)} \\
x_{(2,1)} & x_{(2,2)}
\end{bmatrix}\\
\\
x_1=x+2 \\
x_2=x-2 \\
\\
\begin{aligned}
x_3&=x_1\times{x_2} \\
&=(x+2)(x-2) \\
&=x^2-4
\end{aligned} \\
\\
\begin{aligned}
y&=\text{sum}(x_3) \\
&=x_{3,(1,1)}+x_{3,(1,2)}+x_{3,(2,1)}+x_{3,(2,2)}
\end{aligned} \\
\\
\text{x.grad}=\begin{bmatrix}
\frac{\partial{y}}{\partial{x_{(1,1)}}} & \frac{\partial{y}}{\partial{x_{(1,2)}}} \\
\frac{\partial{y}}{\partial{x_{(2,1)}}} & \frac{\partial{y}}{\partial{x_{(2,2)}}}
\end{bmatrix} \\
\\
\frac{dy}{dx}=2x
\end{gathered}$$

In [5]:
print(x.grad)

tensor([[2., 4.],
        [6., 8.]])


In [6]:
print(x)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [7]:
x3.numpy()

RuntimeError: ignored

In [8]:
x3.detach_().numpy()

array([[-3.,  0.],
       [ 5., 12.]], dtype=float32)