<a href="https://colab.research.google.com/github/wjdrnqja9/TIL/blob/main/deep_learning/07_02_gradient_descent_checkpoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Gradient Descent

In [1]:
import torch
import torch.nn.functional as F

In [2]:
target = torch.FloatTensor([[.1, .2, .3],
                            [.4, .5, .6],
                            [.7, .8, .9]])

In [3]:
x = torch.rand_like(target)
# This means the final scalar will be differentiate by x.
x.requires_grad = True
# You can get gradient of x, after differentiation.

x

tensor([[0.0698, 0.3586, 0.2421],
        [0.8683, 0.3019, 0.6978],
        [0.7625, 0.0019, 0.5318]], requires_grad=True)

In [4]:
loss = F.mse_loss(x, target)

loss

tensor(0.1193, grad_fn=<MseLossBackward0>)

In [5]:
threshold = 1e-5
learning_rate = 1.
iter_cnt = 0

while loss > threshold:
    iter_cnt += 1
    
    loss.backward() # Calculate gradients.

    x = x - learning_rate * x.grad
    
    # You don't need to aware this now.
    x.detach_()
    x.requires_grad_(True)
    
    loss = F.mse_loss(x, target)
    
    print('%d-th Loss: %.4e' % (iter_cnt, loss))
    print(x)

1-th Loss: 7.2191e-02
tensor([[0.0765, 0.3233, 0.2550],
        [0.7643, 0.3459, 0.6760],
        [0.7486, 0.1792, 0.6136]], requires_grad=True)
2-th Loss: 4.3671e-02
tensor([[0.0817, 0.2959, 0.2650],
        [0.6833, 0.3802, 0.6591],
        [0.7378, 0.3172, 0.6773]], requires_grad=True)
3-th Loss: 2.6418e-02
tensor([[0.0858, 0.2746, 0.2728],
        [0.6204, 0.4068, 0.6460],
        [0.7294, 0.4245, 0.7268]], requires_grad=True)
4-th Loss: 1.5981e-02
tensor([[0.0889, 0.2580, 0.2788],
        [0.5714, 0.4275, 0.6358],
        [0.7229, 0.5079, 0.7653]], requires_grad=True)
5-th Loss: 9.6677e-03
tensor([[0.0914, 0.2451, 0.2835],
        [0.5333, 0.4436, 0.6278],
        [0.7178, 0.5728, 0.7952]], requires_grad=True)
6-th Loss: 5.8484e-03
tensor([[0.0933, 0.2351, 0.2872],
        [0.5037, 0.4561, 0.6216],
        [0.7138, 0.6233, 0.8185]], requires_grad=True)
7-th Loss: 3.5379e-03
tensor([[0.0948, 0.2273, 0.2900],
        [0.4806, 0.4659, 0.6168],
        [0.7108, 0.6626, 0.8366]], requi